BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[mstitmuntnfo] (
    [rowid] INT NOT NULL IDENTITY(1,1),
    [itmuntcd] NVARCHAR(1000) NOT NULL,
    [itmuntnm] NVARCHAR(1000) NOT NULL,
    [itmuntshnm] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [mstitmuntnfo_pkey] PRIMARY KEY CLUSTERED ([rowid])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
