BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[mstpartycat] (
    [rowid] INT NOT NULL IDENTITY(1,1),
    [pcatcd] NVARCHAR(1000) NOT NULL,
    [pcatnm] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [mstpartycat_pkey] PRIMARY KEY CLUSTERED ([rowid])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
