BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[mstdatelocknfo] (
    [rowid] INT NOT NULL IDENTITY(1,1),
    [lockcd] NVARCHAR(1000) NOT NULL,
    [untcd] NVARCHAR(1000) NOT NULL,
    [lockdt] DATE NOT NULL,
    [sts] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [mstdatelocknfo_pkey] PRIMARY KEY CLUSTERED ([rowid])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
