BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[mstsyslednfo] (
    [rowid] INT NOT NULL IDENTITY(1,1),
    [sysledcd] NVARCHAR(1000) NOT NULL,
    [syslednm] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [mstsyslednfo_pkey] PRIMARY KEY CLUSTERED ([rowid])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
